version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: decode-gov
    environment:
      POSTGRES_DB: decode-gov
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - decode-gov:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - decode-gov-network

networks:
  decode-gov-network:
    name: decode-gov-network
    driver: bridge

volumes:
  decode-gov: